### ISSUE TITLE
地域版プロジェクトのデータ更新

### ISSUE THREAD

**Issue by yokinist** [codeforjapan/stopcovid19#17]
## 提案概要 / What
- 地域版プロジェクトのデータ(data.json)を更新する

## 提案理由 / Why
- 現状3週間ほど前のデータなので
- 更新分が結構あるはずなので
- 市町村版も増えてきている
- 自治体などはスプレッドシートではなくサイトを閲覧して確認するケースがある

## 参考リンク / Reference link
- https://hackmd.io/9TTyyjchR8ufuMd9z08Rcg
- https://docs.google.com/spreadsheets/d/1c50h3YtbsCiHiKOh4cyJQYL-21Vow3X7b8tRoAceVMA/edit#gid=0

**Comment by yokinist** [comment]
```
- 市町村版も増えてきている
- 自治体などはスプレッドシートではなくサイトを閲覧して確認するケースがある
```
の点から自動更新がいいのではという流れになっている

**Comment by yokinist** [comment]
今週後半でよければ自分対応します

**Comment by homata** [comment]
対応お願いできますか？
現時点は手動で更新しておきます

**Comment by yokinist** [comment]
@homata 承知しました更新ありがとうございます！

**Comment by homata** [comment]
よろしくお願いいたします。
いろいろ突貫の間に合わせで作ったので、おかしなところもあるので気になるところは直してください
