### ISSUE TITLE
最終更新日の不一致

### ISSUE THREAD

**Issue by ocean3fish** [codeforjapan/stopcovid19#20]
## 改善詳細 / Details of Improvement
- [地域マップ](https://stopcovid19.code4japan.org/) と [地域詳細一覧](https://stopcovid19.code4japan.org/tables/area-tables) の最終更新日が異なっている
- データソースは [こちらのスプレッドシート](https://docs.google.com/spreadsheets/u/1/d/1c50h3YtbsCiHiKOh4cyJQYL-21Vow3X7b8tRoAceVMA/edit) で共通しているはずなので最終更新日は揃うはず
- [関連情報](https://stopcovid19.code4japan.org/information) はソースが多すぎて更新を追えないと思うので最終更新日表示は消しても良さそう

### 地域マップ
<img width="355" alt="スクリーンショット 2020-04-28 20 35 17" src="https://user-images.githubusercontent.com/4206675/80482818-de3ba180-898f-11ea-82a6-cf32ad2bdf31.png">

### 地域詳細一覧
<img width="358" alt="スクリーンショット 2020-04-28 20 35 09" src="https://user-images.githubusercontent.com/4206675/80482859-ef84ae00-898f-11ea-8db8-1dcc971f31e7.png">

### 関連情報
<img width="294" alt="スクリーンショット 2020-04-28 20 37 18" src="https://user-images.githubusercontent.com/4206675/80482942-180ca800-8990-11ea-9a90-65251425da1e.png">

**Comment by homata** [comment]
あ、バグってますね。更新日の表示は一個所にした方がよさそうです

**Comment by homata** [comment]
修正しました。
