### ISSUE TITLE
滋賀県版の表記に関して

### ISSUE THREAD

**Issue by YuseiIto** [codeforjapan/stopcovid19#4]
現在滋賀県版は「滋賀県公式 + Code for Kusatsu」と表記頂いています。
確かにC4Kは参加していますが、それ以外に参加している方がいること、県公式リリースの表記に合わせたいことから、「滋賀県公式 + 県内有志チーム」との表記に変更いただくようお願いいたします。

**Comment by homata** [comment]
ご指摘ありがとうございます。
「滋賀県公式 + 県内有志チーム」に表記を修正しました。

**Comment by munierujp** [comment]
このイシューは既にクローズできませんか？

**Comment by homata** [comment]
確認おそくなりました。クローズします
